# Generated by Django 2.0 on 2019-05-15 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_end_date', models.DateField(null=True)),
                ('subscription_start_date', models.DateField(null=True)),
                ('subscription_type', models.CharField(max_length=50, null=True)),
                ('customer_id', models.CharField(max_length=50, null=True)),
                ('subscription_id', models.CharField(max_length=50, null=True)),
                ('plan_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
