# Generated by Django 2.0 on 2019-05-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='card_source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
