# Generated by Django 2.0 on 2019-05-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_buisness',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_freelancing',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_freemium',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='customer_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
