# Generated by Django 2.0 on 2019-04-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='is_buisness',
            new_name='is_trial',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_freelancing',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_freemium',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sub_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_end_date',
            field=models.DateField(null=True),
        ),
    ]
