# Generated by Django 2.0 on 2019-04-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20190424_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='customer_card_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
