# Generated by Django 2.0 on 2019-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_customer_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='sub_start_date',
            field=models.DateField(null=True),
        ),
    ]
