# Generated by Django 2.0 on 2019-06-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionplan_card_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_switch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sub_switch_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
