# Generated by Django 2.0 on 2019-05-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionplan_sub_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='customer_card_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='sub_end_date',
            new_name='subscription_end_date',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='sub_start_date',
            new_name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_end_date',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
