# Generated by Django 2.0 on 2019-06-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20190614_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='sub_switch_date',
            field=models.DateField(null=True),
        ),
    ]
