# Generated by Django 2.0 on 2019-08-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20190617_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_switch',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='sub_switch_date',
        ),
    ]
