# Generated by Django 2.0 on 2019-03-23 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0009_auto_20190321_0313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('transact_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transact_data', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transact_history', to='invoice.ClientInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transact_amount',),
            },
        ),
    ]
