# Generated by Django 2.0 on 2019-06-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ('-transact_date',)},
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='transact_data',
            new_name='transact_date',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='client_id',
        ),
    ]
