# Generated by Django 2.0 on 2019-01-25 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250)),
                ('business_description', models.TextField()),
                ('business_number', models.CharField(blank=True, max_length=250)),
                ('business_address', models.CharField(max_length=250)),
                ('business_logo', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buiness_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
       
    ]
