# Generated by Django 2.0 on 2019-01-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190126_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='account_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
