# Generated by Django 2.0 on 2019-01-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190130_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='approved_account',
            field=models.BooleanField(default=False),
        ),
    ]
