# Generated by Django 2.0 on 2019-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessinfo_cac_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='has_uploaded_bank_details',
            field=models.BooleanField(default=False),
        ),
    ]
