# Generated by Django 2.0 on 2019-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_businessinfo_has_uploaded_bank_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='business_city',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='business_state',
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='business_size',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='business_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='gender',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='phone_number',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='state',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
