# Generated by Django 2.0 on 2019-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190201_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='cac_number',
            field=models.IntegerField(null=True),
        ),
    ]
