# Generated by Django 2.0 on 2019-02-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190201_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='cac_number',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
