# Generated by Django 2.0 on 2019-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190201_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='business_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
