# Generated by Django 2.0 on 2019-04-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190201_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='business_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
