# Generated by Django 2.0 on 2019-08-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190201_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='business_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='cac_number',
            field=models.CharField(max_length=250),
        ),
    ]
