# Generated by Django 2.0 on 2019-03-30 23:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('product_id', models.IntegerField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='InventoryProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_avaliable', models.BooleanField(default=True)),
                ('link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='inventoryinvoices',
            name='inventories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_invoicesss', to='inventory_system.InventoryProducts'),
        ),
        migrations.AddField(
            model_name='inventoryinvoices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_productss', to=settings.AUTH_USER_MODEL),
        ),
    ]
