# Generated by Django 2.0 on 2019-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_auto_20190514_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryinvoices',
            name='inventories',
        ),
        migrations.AddField(
            model_name='inventoryinvoices',
            name='product_list',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
