# Generated by Django 2.0 on 2019-08-01 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_auto_20190729_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryinvoices',
            name='product_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=[], size=None),
            preserve_default=False,
        ),
    ]
