# Generated by Django 2.0 on 2019-08-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0004_auto_20190801_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproducts',
            name='link',
        ),
    ]
