# Generated by Django 2.0 on 2019-08-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0005_remove_inventoryproducts_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryinvoices',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryproducts',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
    ]
