# Generated by Django 2.0 on 2019-01-30 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDEtails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=250)),
                ('card_holder_number', models.CharField(max_length=250)),
                ('card_holder_expiry_date', models.CharField(max_length=10)),
                ('card_holder_cvc', models.CharField(max_length=5)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
