# Generated by Django 2.0 on 2019-01-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_bankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='card_id',
        ),
        migrations.DeleteModel(
            name='CardDEtails',
        ),
    ]
