# Generated by Django 2.0 on 2019-03-13 14:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(max_length=50)),
                ('reminder_type', models.CharField(blank=True, default='', max_length=50)),
                ('reminder_set_day', models.CharField(blank=True, default='', max_length=50)),
                ('days_of_the_week', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('client_phone_number', models.CharField(max_length=50)),
                ('client_address', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('invoice_type', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('is_pending', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.TextField(blank=True)),
                ('link', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('client_name', models.CharField(blank=True, max_length=50)),
                ('client_phone_number', models.CharField(blank=True, max_length=50)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_address', models.CharField(blank=True, max_length=50)),
                ('project_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=20)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('can_create_reminder', models.BooleanField(default=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reminder', to='invoice.ClientInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='automatedreminder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_reminder', to='invoice.Invoice'),
        ),
    ]
