# Generated by Django 2.0 on 2019-03-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_phone_number',
        ),
    ]
