# Generated by Django 2.0 on 2019-03-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedreminder',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='approved',
        ),
    ]
