# Generated by Django 2.0 on 2019-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20190317_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='link',
            field=models.URLField(),
        ),
    ]
