# Generated by Django 2.0 on 2019-03-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20190317_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_reminder', to='invoice.ClientInfo'),
        ),
    ]
