# Generated by Django 2.0 on 2019-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20190318_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
