# Generated by Django 2.0 on 2019-03-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20190318_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
