# Generated by Django 2.0 on 2019-03-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20190318_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
